### ISSUE TITLE
Benchmarks for pairings are not executed

### ISSUE THREAD

**Issue by mmaker** [arkworks-rs/curves#146]
## Summary of Bug

Can't find any `*Pairing*` match in the benchmark output. Even running `cargo criterion --message-output=json` does not seem to produce any string matching "Pairing" in the `id`, as one would expect reading ark-bench-templates. 

## Steps to Reproduce
```
$ cargo bench Pairing
```

**Comment by mmaker** [comment]
Fixed in https://github.com/arkworks-rs/algebra/pull/586.

**Comment by mmagician** [comment]
Fixed indeed.
