### ISSUE TITLE
Investigate methods to lower the CI time

### ISSUE THREAD

**Issue by ValarDragon** [arkworks-rs/curves#33]
Currently the CI is taking on the order of 19-20 minutes to build all the crates and test them. We should see if there are thing we can do to reduce this. (E.g. split up the curves and do more CI tests in parallel, get incremental builds / caching, etc.)

**Comment by Pratyush** [comment]
We could try to do tests in parallel in separate jobs, maybe using a strategy like this: https://dev.to/dwieeb/parallelizing-jest-with-github-actions-20m0

**Comment by Pratyush** [comment]
This is done in #52
