### ISSUE TITLE
Add TweedleDee/Dum

### ISSUE THREAD

**Issue by Pratyush** [arkworks-rs/curves#4]
These curves are implemented in the [O(1)-labs fork](https://github.com/o1-labs/zexe/tree/master/algebra/src/tweedle), so porting them over is a simple copy-paste job.

**Comment by weikengchen** [comment]
Should we change something in the license/or files to credit O(1)-labs? The license in their forks is identical to Zexe's.

**Comment by daira** [comment]
At https://github.com/arkworks-rs/curves/pull/8#issuecomment-738156735 I wrote:
> At ECC we have switched entirely to [Pallas/Vesta](https://electriccoin.co/blog/the-pasta-curves-for-halo-2-and-beyond/) for use with Halo 2, and we don't intend to deploy the Tweedledum/Tweedledee curves or promote their adoption. Pallas/Vesta are implemented in #21, so I think this can be closed.

**Comment by daira** [comment]
I think this can be closed, since #8 has been closed.
