### ISSUE TITLE
bls12-377 scalar field "generator" has wrong order

### ISSUE THREAD

**Issue by alex-ozdemir** [arkworks-rs/curves#57]
## Summary of Bug

Your bls12-377 curve (scalar field of order `p = 52435875175126190479447740508185965837690552500527637822603658699938581184513`) uses `11` as a multiplicative generator for this subgroup, but `11` actually has order `(p-1)/35`. Using `22` as the generator would do the trick.

Code pointer: [https://github.com/arkworks-rs/curves/blob/master/bls12_377/src/fields/fr.rs#L56-L58](https://github.com/arkworks-rs/curves/blob/master/bls12_377/src/fields/fr.rs#L56-L58)

## Version

0.2

## Steps to Reproduce

Not sure if `GENERATOR` means something different than I expected. Assuming this should be fixed, I'm happy to submit a PR.

**Comment by weikengchen** [comment]
@Pratyush

**Comment by Pratyush** [comment]
Hm yes, it seems that 11 is not a generator of the multiplicative group. A PR to fix this would be much appreciated!
