### ISSUE TITLE
Secp384r1 discussion

### ISSUE THREAD

**Issue by burdges** [arkworks-rs/curves#82]
Estonian e-Identity keys sign using ECDSA on secp384r1.  

It's [unethical](https://twitter.com/jeffburdges/status/1382959262343696384) to place human identifying keys on a transparent blockchain of course, like say https://github.com/LogvinovLeon/estid-sig proposes, but people could've off-chain usages, so perhaps secp384r1 makes sense here?

We could also identify pairing friendly curves whose group order agreed with the base field of secp384r1, so that some ECDSA gadget could verify an Estonian e-Identity signature in zero-knowledge.  It's still tricky to use this on-chain, but much less awful..

What do people think?  

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rubdos** [comment]
#142 implements the secp384r1 curve.
